### PR TITLE
chore: fix version and update lockfile

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/Homebrew/homebrew-core/pull/181186

cc @quantumsheep

### CODE REVIEW

**Comment by quantumsheep** [comment]
I always forget 😢

**Comment by chenrui333** [comment]
it might be better to add RELEASE.md, and just follow from there, what do you think?

**Comment by chenrui333** [comment]
you also need to mark 4.5.1 as latest release :)

image

**Comment by chenrui333** [comment]
Thanks again for the version fix!

**Pull request merged**
