### PR TITLE
add nix support and installation instructions for nix

### PR DESCRIPTION
**Pull request by jnats**

### CODE REVIEW

**Comment by ihatethefrench** [comment]
Not sure why this took me so long to get to 😅
I'll see what I can do, I've been meaning to package my first app for nixpkgs for a while now!

**Comment by ihatethefrench** [comment]
> Not sure why this took me so long to get to sweat_smile I'll see what I can do, I've been meaning to package my first app for nixpkgs for a while now!

https://github.com/NixOS/nixpkgs/pull/180959

Fingers crossed :)

**Comment by quantumsheep** [comment]
> [NixOS/nixpkgs#180959](https://github.com/NixOS/nixpkgs/pull/180959)
> 
> Fingers crossed :)

Thanks a lot! Also how to update the flake ?

**Comment by ihatethefrench** [comment]
Every time the flake is built/installed, it'll fetch from the latest version in the git repository. You can update the versions of the dependencies the flake pulls by running `nix flake update`, which also updates the lockfile so anyone building from the flake will always pull the same versions of said dependencies

**Pull request merged**
