### PR TITLE
Add new option

### PR DESCRIPTION
**Pull request by nodauf**
Add the option `-a`, `--ssh-arguments` to directly pass arguments to the ssh command.
I personally use this option mostly for port forwarding or configuring a ssh proxy socks.

### CODE REVIEW

**Comment by quantumsheep** [comment]
Hey, thanks a lot for contributing!

Not sure if it works with multiple arguments, did you tried?

**Comment by nodauf** [comment]
Nice catch. Indeed, it was not working. Now it should. I have tried with multiple arguments

**Comment by quantumsheep** [comment]
It will not work if you have something like `-a"--something 'a b c'"`. Use a library like [shlex](https://github.com/google/shlex) (it's archived but works well).

**Comment by nodauf** [comment]
Ok I will give it a look and do this properly.

**Comment by nodauf** [comment]
The last commit is now using shlex.  The arguments are properly sent to ssh:
image

**Comment by quantumsheep** [comment]
Fantastic ! Thanks ❤️

**Pull request merged**
